name: Build 31 - MacOS arm64
on: workflow_dispatch
jobs:
  wheels-macos:
    runs-on: macos-11
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    arch: [x86_64, arm64]
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        curl -O -L https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz
        tar xfz boost_1_80_0.tar.gz
        cd boost_1_80_0
        ./bootstrap.sh
        ./b2 architecture=arm address-model=64 -s NO_LZMA=1 -s NO_ZSTD=1 abi=aapcs install
        echo "ls -l /usr/local"
        ls -l /usr/local
        echo "ls -l /usr/local/lib"
        ls -l /usr/local/lib
        lipo /usr/local/lib/libboost_filesystem.dylib -info
        lipo /usr/local/lib/libboost_*.dylib -info
    - name: Build ORE
      run: |
        pwd
        tar xfz ore.00.tgz
        tar xfz oreswig.01.tgz
        cp setup.31.py oreswig/OREAnalytics-SWIG/Python/setup.py
        cp oreanalytics-config.30 oreswig/OREAnalytics-SWIG/oreanalytics-config
        cd ore
        mkdir build
        cd build
        cmake -DBUILD_DOC=OFF -DCMAKE_OSX_ARCHITECTURES=arm64 ..
        cmake --build .
        cmake --install .
    - name: Build ORE wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        #CIBW_BUILD: cp310-macosx_arm64
        CIBW_SKIP: cp36-*
        CIBW_ARCHS_MACOS: arm64
        CXXFLAGS: -std=c++14 -g0 -O3
        CIBW_BUILD_VERBOSITY: 2
        CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
          DYLD_LIBRARY_PATH=/usr/local/lib delocate-listdeps {wheel} &&
          DYLD_LIBRARY_PATH=/usr/local/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}
      with:
        package-dir: oreswig/OREAnalytics-SWIG/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-macos-arm64
        path: ./wheelhouse/*.whl
