name: Build 23 - Linux - cmake x86_64 musllinux
on: workflow_dispatch
jobs:
  wheels-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build ORE
      run: |
        ./build_ore.23.sh
    - name: Build ORE wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        ORE: /home/runner/work/ore-wheels/ore-wheels/ore
        CIBW_BUILD: cp310-musllinux_x86_64
        CIBW_ARCHS_LINUX: x86_64
        CIBW_BUILD_VERBOSITY: 2
        CIBW_BEFORE_ALL_LINUX: ./before_all_linux.22.sh
        # FIXME manylinux works with -O3, musllinux fails, trying -O2
        #CIBW_ENVIRONMENT_LINUX: CXXFLAGS="-O3 -g0"
        CIBW_ENVIRONMENT_LINUX: CXXFLAGS="-O2 -g0"
        CIBW_ENVIRONMENT_PASS_LINUX: CXXFLAGS
      with:
        package-dir: /home/runner/work/ore-wheels/ore-wheels/oreswig/OREAnalytics-SWIG/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-linux-musllinux-x86_64
        path: ./wheelhouse/*.whl
