name: Build Wheels 0
on: workflow_dispatch
jobs:
  wheels-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Setup Boost
      run: |
        $Url = "https://boostorg.jfrog.io/artifactory/main/release/1.80.0/binaries/boost_1_80_0-msvc-14.3-64.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
        Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\local\boost"
    - name: Build ORE
#      env:
#        Boost_ROOT: C:\local\boost
      run: |
        Expand-Archive -Path ore.00.zip -DestinationPath C:\local
#        cd C:\local\ORE-0.1.1-Source
#        mkdir build2
#        cd build2
#        cmake  -G "Visual Studio 17 2022" -A x64 ..
#        cmake --build . --config Release --verbose
    - name: Unpack ORE libs
      run: |
        Expand-Archive -Path ore.01.zip -DestinationPath C:\local
    - name: Unpack ORE-SWIG
      run: |
        Expand-Archive -Path oreswig.00.zip -DestinationPath .
    - name: Build ORE wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        BOOST_ROOT: C:\local\boost
        BOOST_LIB: C:\local\boost\lib64-msvc-14.3
        ORE_DIR: C:\local\ore
        CIBW_SKIP: cp36-*
        CIBW_ARCHS_WINDOWS: AMD64
        CIBW_BUILD_VERBOSITY: 2
      with:
        package-dir: oreswig/OREAnalytics-SWIG/Python
