name: Build 21 - Linux - cmake i686 manylinux
on: workflow_dispatch
jobs:
  wheels-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12
    - name: Build ORE
      run: |
        ./build_ore.22.sh
    - name: Build ORE wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_BUILD: "*-manylinux*"
        CIBW_SKIP: cp36-*
        #CIBW_BUILD: cp37-manylinux_x86_64
        #CIBW_BUILD: cp38-manylinux_x86_64
        #CIBW_BUILD: cp39-manylinux_x86_64
        #CIBW_BUILD: cp310-manylinux_x86_64
        #CIBW_BUILD: cp311-manylinux_x86_64
        CIBW_ARCHS_LINUX: i686
        CIBW_BUILD_VERBOSITY: 2
        CIBW_BEFORE_ALL_LINUX: ./before_all_linux.22.sh
        CIBW_ENVIRONMENT_LINUX: CXXFLAGS="-O0 -g0 -j0"
        CIBW_ENVIRONMENT_PASS_LINUX: CXXFLAGS
      with:
        package-dir: /home/runner/work/ore-wheels/ore-wheels/oreswig/OREAnalytics-SWIG/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-linux-manylinux-i686
        path: ./wheelhouse/*.whl
