name: Build 20 - Linux - cmake x86_64 manylinux
on: workflow_dispatch
jobs:
  wheels-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
#    - name: Install eigen
#      run: |
#        sudo apt-get update
#        sudo apt-get install -f -y libeigen3-dev
    - name: Build ORE
      run: |
        ./build_ore.22.sh
    - name: Build ORE wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_BUILD: "*-manylinux*"
        CIBW_SKIP: cp36-*
        #CIBW_BUILD: cp37-manylinux_x86_64
        #CIBW_BUILD: cp38-manylinux_x86_64
        #CIBW_BUILD: cp39-manylinux_x86_64
        #CIBW_BUILD: cp310-manylinux_x86_64
        #CIBW_BUILD: cp311-manylinux_x86_64
        CIBW_ARCHS_LINUX: x86_64
        CIBW_BUILD_VERBOSITY: 2
        CIBW_BEFORE_ALL_LINUX: ./before_all_linux.22.sh
        CIBW_ENVIRONMENT_LINUX: CXXFLAGS="-O3 -g0"
        CIBW_ENVIRONMENT_PASS_LINUX: CXXFLAGS
      with:
        package-dir: /home/runner/work/ore-wheels/ore-wheels/oreswig/OREAnalytics-SWIG/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-linux-manylinux-x86_64
        path: ./wheelhouse/*.whl
