name: Build 02 - Windows - cmake Win32 & x64
on: workflow_dispatch
jobs:
  wheels-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - arch: AMD64
            platform: x64
            boost-lib: C:\local\boost\lib64-msvc-14.3
          - arch: x86
            platform: Win32
            boost-lib: C:\local\boost\lib32-msvc-14.3
    steps:
    - uses: actions/checkout@v3
    - name: Setup Boost 32 bit
      run: |
        $Url = "https://boostorg.jfrog.io/artifactory/main/release/1.80.0/binaries/boost_1_80_0-msvc-14.3-32.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
        Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\local\boost"
    - name: Setup Boost 64 bit
      run: |
        $Url = "https://boostorg.jfrog.io/artifactory/main/release/1.80.0/binaries/boost_1_80_0-msvc-14.3-64.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
        Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\local\boost"
###################################
# build the libs using cmake
###################################
    - name: Build ORE
      env:
        Boost_ROOT: C:\local\boost
      run: |
        Expand-Archive -Path ore.00.zip -DestinationPath C:\local
        cd C:\local\ore
        mkdir build2
        cd build2
        cmake -DBUILD_DOC=OFF -DMSVC_LINK_DYNAMIC_RUNTIME=OFF -G "Visual Studio 17 2022" -A ${{ matrix.platform }} ..
        cmake --build . --config Release --verbose
    - name: Unpack ORE-SWIG
      run: |
        Expand-Archive -Path oreswig.02.zip -DestinationPath .
###################################
# prebuilt libs FIXME - change runtime from dynamic to static, add 32 bit
###################################
#    - name: Unpack ORE source
#      run: |
#        Expand-Archive -Path ore.00.zip -DestinationPath C:\local
#    - name: Unpack ORE libs
#      run: |
#        Expand-Archive -Path ore.01.zip -DestinationPath C:\local
#    - name: Unpack ORE-SWIG
#      run: |
#        Expand-Archive -Path oreswig.01.zip -DestinationPath .
###################################
    - name: Build ORE wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        BOOST_ROOT: C:\local\boost
        BOOST_LIB: ${{ matrix.boost-lib }}
        ORE_DIR: C:\local\ore
        ORE_STATIC_RUNTIME: 1
        CIBW_SKIP: cp36-*
        CIBW_ARCHS_WINDOWS: ${{ matrix.arch }}
        CIBW_BUILD_VERBOSITY: 2
      with:
        package-dir: oreswig/OREAnalytics-SWIG/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-windows-${{ matrix.arch }}
        path: ./wheelhouse/*.whl
