name: Build 20 - Linux - cmake x86_64 manylinux
on: workflow_dispatch
jobs:
  wheels-linux:
    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        arch: [x86_64, i686]
#        image: [manylinux, musllinux]
    steps:
    - uses: actions/checkout@v3
    - name: Unpack ORE and ORE-SWIG
      run: |
        tar xfz ore.00.tgz
        tar xfz oreswig.01.tgz
    - name: Build ORE wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        #CIBW_BUILD: "*-${{ matrix.image }}*"
        CIBW_BUILD: "*-manylinux*"
        CIBW_SKIP: cp36-*
        #CIBW_ARCHS_LINUX: ${{ matrix.arch }}
        CIBW_ARCHS_LINUX: x86_64
        CIBW_BUILD_VERBOSITY: 2
        CIBW_BEFORE_ALL_LINUX: ./before_all_linux.sh
        #CIBW_ENVIRONMENT_LINUX: CXXFLAGS=${{ matrix.arch == 'x86_64' && '"-O3 -g0"' || '"-O1 -g0"' }}
        CIBW_ENVIRONMENT_LINUX: CXXFLAGS='"-O3 -g0"'
        CIBW_ENVIRONMENT_PASS_LINUX: CXXFLAGS
      with:
        package-dir: oreswig/OREAnalytics-SWIG/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        #name: wheels-linux-${{ matrix.image }}-${{ matrix.arch }}
        name: wheels-linux-manylinux-x86_64
        path: ./wheelhouse/*.whl
