name: Build 22 - Linux - cmake x86_64 musllinux
on: workflow_dispatch
jobs:
  wheels-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
    - name: Build ORE
      run: |
        ./build_ore.22.sh
    - name: Build ORE wheels
      uses: pypa/cibuildwheel@v2.11.1
      env:
        CIBW_BUILD: "*-musllinux*"
        CIBW_SKIP: cp36-*
        #CIBW_BUILD: cp37-musllinux_x86_64
        #CIBW_BUILD: cp38-musllinux_x86_64
        #CIBW_BUILD: cp39-musllinux_x86_64
        #CIBW_BUILD: cp310-musllinux_x86_64
        #CIBW_BUILD: cp311-musllinux_x86_64
        CIBW_ARCHS_LINUX: x86_64
        CIBW_BUILD_VERBOSITY: 2
        CIBW_BEFORE_ALL_LINUX: ./before_all_linux.22.sh
        CIBW_ENVIRONMENT_LINUX: CXXFLAGS="-O2 -g0"
        CIBW_ENVIRONMENT_PASS_LINUX: CXXFLAGS
      with:
        package-dir: /home/runner/work/ore-wheels/ore-wheels/oreswig/OREAnalytics-SWIG/Python
    - name: Save wheels as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: wheels-linux-musllinux-x86_64
        path: ./wheelhouse/*.whl
